# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_info',
            old_name='email',
            new_name='email_address',
        ),
        migrations.AlterField(
            model_name='image',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableau.email_info'),
        ),
    ]
