# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0004_delete_email_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
