# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0008_auto_20160530_2320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
